FROM python:3.11-slim

RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN pip3 install --upgrade pip
WORKDIR /app

COPY ./src /app/src/
COPY ./README.md ./pyproject.toml ./conftest.py /app/

RUN ls -l /app

RUN pip3 install pytest .

# CMD python3 -m pytest -vv
