FROM python:3.11-slim

WORKDIR /app

# Install update pip and hatch to build package
RUN pip3 install --upgrade pip hatch

# Copy necessary files from project root (but leave out others like secrets files, etc)
COPY README.md pyproject.toml conftest.py ./
# Copy source code
COPY ./src/ ./src/
COPY ./tests/ ./tests/

# Setup hatch env which will install deps
RUN hatch env create test

# Take arg for database URL, specified in docker-compose.yml
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL:-}
ENTRYPOINT hatch --env test run pytest tests/ -vv --database-url "$DATABASE_URL"
